# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.everis.com:
    container_name: orderer.everis.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      #- ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/everis.com/orderers/orderer.everis.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/everis.com/orderers/orderer.everis.com/tls/:/var/hyperledger/orderer/tls
    - orderer.everis.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.pagos.everis.com:
    container_name: peer0.pagos.everis.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.pagos.everis.com
      - CORE_PEER_ADDRESS=peer0.pagos.everis.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pagos.everis.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pagos.everis.com:7051
      - CORE_PEER_LOCALMSPID=PagosMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/pagos.everis.com/peers/peer0.pagos.everis.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/pagos.everis.com/peers/peer0.pagos.everis.com/tls:/etc/hyperledger/fabric/tls
        - peer0.pagos.everis.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053
      - 7055:6060

  peer1.pagos.everis.com:
    container_name: peer1.pagos.everis.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.pagos.everis.com
      - CORE_PEER_ADDRESS=peer1.pagos.everis.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.pagos.everis.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.pagos.everis.com:7051
      - CORE_PEER_LOCALMSPID=PagosMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/pagos.everis.com/peers/peer1.pagos.everis.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/pagos.everis.com/peers/peer1.pagos.everis.com/tls:/etc/hyperledger/fabric/tls
        - peer1.pagos.everis.com:/var/hyperledger/production
    ports:
      - 7061:7051
      - 7063:7053
      - 7065:6060

  peer0.cobros.everis.com:
    container_name: peer0.cobros.everis.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.cobros.everis.com
      - CORE_PEER_ADDRESS=peer0.cobros.everis.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.cobros.everis.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.cobros.everis.com:7051
      - CORE_PEER_LOCALMSPID=CobrosMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/cobros.everis.com/peers/peer0.cobros.everis.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/cobros.everis.com/peers/peer0.cobros.everis.com/tls:/etc/hyperledger/fabric/tls
        - peer0.cobros.everis.com:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053
      - 8055:6060

  peer1.cobros.everis.com:
    container_name: peer1.cobros.everis.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.cobros.everis.com
      - CORE_PEER_ADDRESS=peer1.cobros.everis.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.cobros.everis.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.cobros.everis.com:7051
      - CORE_PEER_LOCALMSPID=CobrosMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/cobros.everis.com/peers/peer1.cobros.everis.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/cobros.everis.com/peers/peer1.cobros.everis.com/tls:/etc/hyperledger/fabric/tls
        - peer1.cobros.everis.com:/var/hyperledger/production
    ports:
      - 8061:7051
      - 8063:7053
      - 8065:6060
